import {
  Activity,
  AlertTriangle,
  BarChart3,
  Book,
  BookOpen,
  Bookmark,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  Car,
  Clock,
  Cloud,
  Code,
  Compass,
  CreditCard,
  Database,
  DollarSign,
  Download,
  FileText,
  Flag,
  Folder,
  Gauge,
  Globe,
  GraduationCap,
  HeartHandshake,
  HelpCircle,
  History,
  Inbox,
  Info,
  Key,
  Layers,
  Lightbulb,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  Package,
  ParkingSquare,
  Phone,
  PieChart,
  Plug,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Table,
  Tag,
  Target,
  Terminal,
  TrendingUp,
  Upload,
  User,
  Users,
  Webhook,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon set for pages. Keys are what's stored in pages.icon —
 * add here to expand the picker (keep keys kebab-case lucide names).
 */
export const PAGE_ICONS: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  book: Book,
  rocket: Rocket,
  sparkles: Sparkles,
  zap: Zap,
  plug: Plug,
  webhook: Webhook,
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  cloud: Cloud,
  globe: Globe,
  layers: Layers,
  package: Package,
  gauge: Gauge,
  activity: Activity,
  "file-text": FileText,
  list: List,
  table: Table,
  folder: Folder,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,
  star: Star,
  lock: Lock,
  shield: Shield,
  key: Key,
  bug: Bug,
  "alert-triangle": AlertTriangle,
  info: Info,
  "help-circle": HelpCircle,
  lightbulb: Lightbulb,
  "graduation-cap": GraduationCap,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  search: Search,
  link: Link,
  download: Download,
  upload: Upload,
  history: History,
  clock: Clock,
  calendar: Calendar,
  settings: Settings,
  wrench: Wrench,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  target: Target,
  megaphone: Megaphone,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  "shopping-cart": ShoppingCart,
  briefcase: Briefcase,
  building: Building2,
  "heart-handshake": HeartHandshake,
  users: Users,
  user: User,
  mail: Mail,
  "message-square": MessageSquare,
  phone: Phone,
  inbox: Inbox,
  car: Car,
  parking: ParkingSquare,
};

export function PageIcon({
  name,
  className,
}: {
  name: string | null | undefined;
  className?: string;
}) {
  if (!name) return null;
  const Icon = PAGE_ICONS[name];
  if (!Icon) return null;
  return <Icon className={className} />;
}
